- name: Configure Jamulus Server
  hosts: jamulus_server # need an inventory.ini for this to work
  remote_user: ubuntu
  become: yes

  tasks:
    - name: Set the hostname
      hostname:
        name: jamulus-streamer
          
    - name: Download Jamulus deb
      get_url:
        url: "https://github.com/jamulussoftware/jamulus/releases/download/r3_10_0/jamulus-headless_3.10.0_ubuntu_amd64.deb"
        dest: "/tmp"

    - name: Install Jamulus from a deb file
      ansible.builtin.apt:
        deb: "/tmp/jamulus-headless_3.10.0_ubuntu_amd64.deb"

    - name: Execute apt --fix-broken install
      command: "apt-get --fix-broken install -y"
